apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  namespace: apps
  labels:
    app: nginx
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
