apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: apps
  labels:
    app: java-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: java-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
